# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tv < Formula
  desc "Tag version cli"
  homepage "https://github.com/Miloas/tv"
  version "1.3.5"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miloas/tv/releases/download/1.3.5/tv_Darwin_x86_64.tar.gz"
      sha256 "0c8280efcbd87221fa4422f3228ddd74fa821823b856712f28bc5546a24f902e"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Miloas/tv/releases/download/1.3.5/tv_Linux_x86_64.tar.gz"
      sha256 "8896580aceb1d9c4e4d2229bc2214b8e842e9e78664f3250adf120d8c7186bf6"
    end
  end

  def install
    bin.install "tv"
  end

  test do
    system "#{bin}/tv", "help"
  end
end
