name: build

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
    - run: brew update
    - run: brew audit --formulae Formula/*.rb
    - run: brew install --formulae Formula/*.rb
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        path: |
          ~/Library/Logs/Homebrew/xcnew/
          ~/Library/Logs/Homebrew/class-dump/
    - run: brew test Formula/*.rb
    - run: brew uninstall --formulae Formula/*.rb
