name: build

on: [push]

jobs:
  build:

    runs-on: macOS-11

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build and test
      run: |
        curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh
        brew update >/dev/null
        brew audit ./Formula/*.rb
        brew install -v ./Formula/*.rb
